import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DashboardHeader from "../components/DashboardHeader";
// import ProjectCard from '../components/projectCard'
import BottomPagination from "../components/BottomPagination";
import ProjectCard from "../components/ProjectCard";
import { useQuery } from "urql";
import Footer from "../components/Footer";
import { Key, ReactChild, ReactFragment, ReactPortal } from "react";

let GetProjectsQuery = `
query getProjects {
  projects {
    id
    tag
    title
    type
    target_amount
    endDate
    desc
    current_amount
    cover_img
  }
}
`;

let GetProjectByIdQuery = `
query getProjectById($id: uuid = "") {
  projects_by_pk(id: $id) {
    id
  }
}
`

let ExploreGrid = (props: { fetching: any; error: { message: boolean | ReactChild | ReactFragment | ReactPortal | null | undefined; }; data: { projects: { id: any; title: any; desc: any; current_amount: any; target_amount: any; }[]; }; }) => {

  if (props.fetching) return <div>
    <p className="text-2xl text-gray-600">Loading...</p>

  </div>;
  if (props.error) return <div className="h-3/4 w-full flex items-center justify-center">
    <p className="text-2xl text-gray-600">Oh no... {props.error.message}</p>
  </div>;

  return <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
  {props.data.projects.map(
    (project: {
      id: any;
      title: any;
      desc: any;
      current_amount: any;
      target_amount: any;
    }) => (
      <ProjectCard
        key={project.id}
        id={project.id}
        title={project.title}
        desc={project.desc}
        current_amount={project.current_amount}
        target_amount={project.target_amount}
      />
    )
  )}
  
</div>
}
  
const Explore: NextPage = () => {
  const [result, reexecuteQuery] = useQuery({
    query: GetProjectsQuery,
  });

  const { data, fetching, error } = result;

  return (
    <div className="h-screen">
      <Head>
        <title>Explore Projects - Konan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardHeader title="Explore Projects" />
      <main className="h-4/6">
        <div className="max-w-7xl h-4/5 mx-auto py-6 sm:px-6 lg:px-8">
          <ExploreGrid data={data} fetching={fetching} error={error}/>
          <div className="rounded-lg space-y-10 md:space-y-0 md:grid md:grid-cols-3 "></div>
          <BottomPagination data={data} fetching={fetching} error={error} />
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Explore;
