import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import DashboardHeader from '../components/DashboardHeader'
// import ProjectCard from '../components/projectCard'
import BottomPagination from '../components/BottomPagination'
import ProjectCard from '../components/ProjectCard'

let projects = [

    {
        id: 1,
        name: 'Earthen Bottle',
        href: '#',
    },
    {
        id: 1,
        name: 'Earthen Bottle',
        href: '#',
    },
    {
        id: 1,
        name: 'Earthen Bottle',
        href: '#',
    },
]


const Explore: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Explore Projects - Konan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <DashboardHeader title="Explore Projects"/>
        <main>
          <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
            {projects.map((project) => (
              <ProjectCard key={project.name}/>
              
            ))}
          </div>
            <div className="rounded-lg space-y-10 md:space-y-0 md:grid md:grid-cols-3 ">
             
             
            </div>
            <BottomPagination/>
          </div>
        </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Explore
